language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
env:
  global:
    - RUST_BACKTRACE=1
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - xorg-dev
      - libglu1-mesa-dev
install:
- rustc -Vv
- cargo -V
- travis_wait cargo install cargo-when --force
- export PATH=$HOME/.cargo/bin:$PATH
script:
- cargo check --verbose --all
- rm -rf target/debug/deps/libk-*  # Avoid docmatic problems
- cargo test  --verbose --all
- cargo when --channel nightly bench --all
- cargo when --channel stable doc --all --no-deps --all-features